services:

  init_download_dir:
    image: busybox
    command: >
      sh -c "mkdir -p ${DOWNLOAD_DIR_VOLUME} && chmod 777 ${DOWNLOAD_DIR_VOLUME}"
    volumes:
      - ${DOWNLOAD_DIR_VOLUME}:${DOWNLOAD_DIR_VOLUME}
    environment:
      - DOWNLOAD_DIR_VOLUME=${DOWNLOAD_DIR_VOLUME}
    restart: "no"

  refresh_parsing_data:
    image: busybox


  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    environment:
      - TZ=${TZ}

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - selenium
      - doctranslator
    environment:
      - SELENIUM_URL=${SELENIUM_URL}
      - TZ=${TZ}
      - DOCTRANSLATOR_URL=${DOCTRANSLATOR_URL}
      - DOWNLOAD_DIR=${DOWNLOAD_DIR}
    volumes:
      - ${DOWNLOAD_DIR_VOLUME}:${DOWNLOAD_DIR}
      - ./backend:/app

  selenium:
    image: selenium/standalone-chrome
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOWNLOAD_DIR_VOLUME}:${DOWNLOAD_DIR}
    depends_on:
      - init_download_dir

  doctranslator:
    build: ./docTranstator
    ports:
      - "8001:8001"
    environment:
      - TZ=${TZ}
    tmpfs:
      - /tmp:rw,size=100m